version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/Yeungnam-Nyang-BE2
    overwrite: yes
file_exits_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/Yeungnam-Nyang-BE2/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
