version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/Yeungnam-Nyang-BE2
    overwrites: yes
file_exits_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/Yeungnam-Nyang-BE2/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu